name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pre-commit
        uses: open-turo/action-pre-commit@v3
      - name: Check release notes on pull_request
        if: github.event_name == 'pull_request'
        uses: open-turo/actions-release/lint-release-notes@v4
  test:
    name: Test
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo Noop
        shell: bash
